// <auto-generated />
namespace ICP_ABC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateSubAndTrans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSubAndTrans));
        
        string IMigrationMetadata.Id
        {
            get { return "202109141458536_updateSubAndTrans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
